server:
  port: 9992
spring:
  application:
    name: user

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      

data:
  message: sdfasdfasdfasww44455555
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
