spring:
  datasource:
    username: root
    password:
    url: jdbc-url:jdbc:mysql://localhost:3306/angel_user?characterEncoding=utf8&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
